### ISSUE TITLE
PDF generated reports not saved on device

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-emmunize-malawi#23]
- [ ] The PDF document generated from the children due for vaccines and vaccine doses needed reports are not available on the device. The reports are however sharable via different applications (relates to this issue #8 ). 

Note! Was testing using a tablet.

**Comment by paulinembabu** [comment]
@AnnieMungai  The Reports are Saved on the Device is a folder named Reports. Kindly Check out for this.

**Comment by AnnieMungai** [comment]
@tychus6 please help check this too.

**Comment by AnnieMungai** [comment]
@paulinembabu I confirm that these reports can be found on the reports folder on the device.
