### ISSUE TITLE
Compliance level calculation should exclude expired vaccines

### ISSUE THREAD

**Issue by tychus6** [opensrp/opensrp-client-emmunize-malawi#25]
- [ ] Currently, the compliance level is based on the total number of missed vaccines including the expired vaccines. However, the calculation of this feature should only include missed vaccines(overdue) and exclude  expired vaccines
For example if a child has missed 10 vaccines but 2 have  so far  expired, the  compliance level should read 8 missed vaccines.
Related to issue #9

**Comment by AnnieMungai** [comment]
v.0.2.54debug
Looks great!
