### ISSUE TITLE
Implement the Vaccines Needed Report page

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-emmunize-malawi#6]
**Background**:
The Vaccines needed report will provide a report on the quantity (dosages ) of vaccines required for outreach events (these are events where the health workers go to the community to provide services including immunization). 
- [x] Step 1. Under reports (#3 ), tapping on the **Vaccine Doses Needed** option will navigate user to the **Vaccine Doses Needed** page. 
![Step 1](https://user-images.githubusercontent.com/7522357/106143394-c2199a80-6183-11eb-8106-42934e6b35a0.jpg)

- [x] Step 2. On the **Vaccine Doses Needed page** there will be: 
- A dropdown/ search field to allow selection of a particular village. 
- Calendar (to allow selection of a particular date for the outreach). 
- [x] Step 3. On the form on the **Vaccine Doses Needed** page, the form should allow selection of a particular village- using a smart selection- and date of the outreach. The date cannot be in the past but can be in the future. 
![image](https://user-images.githubusercontent.com/58034047/106571060-c52bd680-6547-11eb-8a60-db13e8176118.png)

- [ ] Step 4 . Once the user has filled in the form with the details, they can tap on **View Report** at the bottom.  This will load the **Vaccine Doses Needed** report with a listing of the required vaccines and respective dosage. The doses displayed are dependant on the total number of children with due and overdue services based on the date the report was run. The report will display: 
- Selected Village
- Selected Outreach date
- A listing of the vaccines and required dosages
![Step 4](https://user-images.githubusercontent.com/7522357/106143388-c0e86d80-6183-11eb-9636-3009ed25b1fd.jpg)

**Comment by tychus6** [comment]
To navigate to the Vaccines needed report page, the steps should be implemented

Step 1. Under reports , add select  the Vaccine needed link
![Step 1](https://user-images.githubusercontent.com/7522357/106142490-99dd6c00-6182-11eb-8047-05ebe8be587e.jpg)

Step 2. The link should take you to a page with a form with the following items
-Filter by Villlage 
(Search/dropdown with a list of villages)
-Calendar (to allow selection of a particular date for the outreach)
![Step 2](https://user-images.githubusercontent.com/7522357/106142522-a4980100-6182-11eb-9139-c94002f8b42b.jpg)

Step 3 .  The form should allow selection of  a particular villages and date for the outreach
![step 3](https://user-images.githubusercontent.com/7522357/106142545-ac57a580-6182-11eb-88f0-c37a85ccf75e.jpg)

Step 4 .Upon submission of the form in Step 3, it should load  a  report with a listing of the required vaccines and respective dosages in terms of the number of children  to be vaccinated.
The report should have  the following;
- Selected Village name
- Selected Outreach date
- An email option to allow emailing of the report as an attachment
- A listing of the vaccines and required dosages
![Step 4](https://user-images.githubusercontent.com/7522357/106142558-b1b4f000-6182-11eb-93f7-9553d38d69c8.jpg)

Step 5. An email option should  be available to email the report as an attachment

![Step 5](https://user-images.githubusercontent.com/7522357/106142579-b5487700-6182-11eb-8c90-66d3d7e026d1.jpg)

**Comment by AnnieMungai** [comment]
v.0.2.50debug

Looks great!
