### ISSUE TITLE
Implement send to email/pdf feature for the children due vaccine report and vaccine doses needed report

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-emmunize-malawi#8]
Background: Once the children due for vaccines report (#5 ) and/ or the Vaccine doses needed report (#6) have been generated, they can be sent to a user via email. To be able to send these reports, they have to be converted to PDF. 
- [x] Generate the Children due for vaccines or the vaccine doses needed report. 
- [x] On the report add an email icon at the top right-hand corner of the page. Tapping on this icon will launch the report export sequence.
![image](https://user-images.githubusercontent.com/58034047/106622785-0393b680-6585-11eb-9365-d4010652c3b0.png)
- [x] To export the report, the report view is converted into a PDF and attached to a draft email in the smartphone’s preferred email client.
- [x] Subject and file name are determined by the report type, village, and date selections. 
- [x] This PDF is a snapshot of children due at a particular time and village.
- [x] The PDF is attached to an email that can be sent out to a preferred recipient. 
- [ ] A copy of the report is saved in the smartphone’s storage, which can be accessed with the smartphone’s file browser.
- [x] Using the same device used to record services, a data connection and syncing are not necessary to generate the report. The email can be saved as a draft until there is access to data.
![image](https://user-images.githubusercontent.com/58034047/106622910-232adf00-6585-11eb-9c0e-bf467598db5f.png).

Note! Email icons can be found [here](https://material.io/resources/icons/?search=email&icon=email&style=outline). 
Here is the [scope document](https://docs.google.com/document/d/11MaCL2VwNaMPhsLqV5y7HwByqZ0Lk4p9/edit) with more details.

**Comment by AnnieMungai** [comment]
@rowo please provide the email icon for this feature. 
![image](https://user-images.githubusercontent.com/58034047/107332990-e8193600-6ac5-11eb-8efb-812abbb66816.png)

**Comment by rowo** [comment]
https://material.io/resources/icons/?search=email&icon=email&style=outline

**Comment by AnnieMungai** [comment]
v.0.2.51 

Most items look good. I will move what is not working to a new issue.
