### ISSUE TITLE
Implement Compliance Levels on the child register page

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-emmunize-malawi#9]
- [x] Compliance status is introduced as a new column in the register. To improve order and reduce visual complexity, we propose using an existing layout from the weight and due columns. 
![image](https://user-images.githubusercontent.com/58034047/108176444-14126800-7113-11eb-9dbe-aecce3fd84c9.png)

- [x] For 0 missed vaccines,  the alert has the same green checkmark as the up-to-date vaccine. This applies for a child up to date but has upcoming vaccines, as well as children with due vaccines. 
- [x] When 1 vaccine is missed, a yellow alert appears - this will apply to children that have missed vaccines i.e. overdue vaccines; the flag shows the number of missed vaccines (1). 
- [x] When 2 or more vaccines are missed, a red alert appears; the flag shows the number of missed vaccines (2+)
- The scope document with more details can be found [here](https://docs.google.com/document/d/1BhKNxH12pHT0f_HSKfGUmpH40l3K3aSl/edit). 
**Note! When computing for the compliance levels, the expired vaccines are ignored and are not factored into the calculations. Only overdue vaccines are considered**

**Comment by AnnieMungai** [comment]
@tychus6 please have a look at this issue and see whether we have captured the essence of this feature. cc @rowo

**Comment by AnnieMungai** [comment]
@HenryRae We could potentially use the flags that were used for ANC--[here](https://github.com/OpenSRP/opensrp-client-anc/tree/master/opensrp-anc/src/main/res/drawable-xxxhdpi)--for this feature, they are quite similar. Are they good to go? cc @rowo.

**Comment by rowo** [comment]
Yea https://github.com/OpenSRP/opensrp-client-anc/blob/master/opensrp-anc/src/main/res/drawable-xxxhdpi/ic_yelllow_flag.png and https://github.com/OpenSRP/opensrp-client-anc/blob/master/opensrp-anc/src/main/res/drawable-xxxhdpi/ic_red_flag.png though maybe a little smaller than the outline version

**Comment by AnnieMungai** [comment]
V0.2.53
Looking great! 
I have however noted the expired vaccines are included in the computation (on issue #25).
